version: '3'
services:
    app-mysql:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: current
            MYSQL_ROOT_HOST: "%"
        networks:
            - default
        volumes:
            - ./mysql/data:/var/lib/mysql
    app-redis:
        image: redis:latest
        networks:
            - default
        ports:
            - "6379:6379"
    app-php:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        networks:
            - default
        volumes:
            - ../current:/usr/share/nginx/html
            - ../current:/packages
        depends_on:
            - app-redis
            - app-mysql
    app-node:
        image: node:latest
        networks:
            - default
        volumes:
            - ../current:/home/node/app
        ports:
            - "8081"
        depends_on:
            - app-nginx
    app-phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        environment:
            - PMA_HOST=app-mysql
        networks:
            - default
        ports:
            - "8080:80"
        depends_on:
            - app-mysql
    app-nginx:
        image: nginx:latest
        networks:
            - default
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ../current:/usr/share/nginx/html
            - ../current:/packages
            - ./nginx/certificates:/etc/nginx/certs
            - ./nginx/http.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/https.conf:/etc/nginx/conf.d/default-ssl.conf
        depends_on:
            - app-php
            - app-phpmyadmin

networks:
    default:
        external:
            name: docker
